# Generated by Django 5.1.3 on 2024-11-15 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_delete_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pole',
            name='title',
        ),
        migrations.AddField(
            model_name='pole',
            name='brand_name',
            field=models.CharField(default='Generic', max_length=25),
        ),
        migrations.AddField(
            model_name='pole',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pole',
            name='material',
            field=models.CharField(choices=[('C', 'Carbon'), ('F', 'Fiberglass')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='pole',
            name='qr_code',
            field=models.ImageField(default='', upload_to='pole_qr_codes'),
        ),
        migrations.AddField(
            model_name='pole',
            name='rental_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pole',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pole',
            name='replacement_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pole')),
                ('return_date', models.DateField(auto_now_add=True)),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
