# Generated by Django 5.1.3 on 2024-11-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_pole_title_pole_brand_name_pole_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pole',
            name='qr_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
