# Generated by Django 5.1.3 on 2024-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pole_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pole',
            name='id',
            field=models.CharField(default='811005', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pole',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
