# Generated by Django 5.1.3 on 2024-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pole_id_alter_pole_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pole',
            name='brand_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pole',
            name='id',
            field=models.CharField(default='177747', max_length=6, primary_key=True, serialize=False),
        ),
    ]
