# Generated by Django 5.1.3 on 2024-11-16 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userinformation_remove_note_author_alter_pole_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='late_fee',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='return_date',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='parent_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='parent_phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='under_age',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pole',
            name='id',
            field=models.CharField(default='684336', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rental',
            name='pole',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pole'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='renter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
