
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"   # Frontend React app will be accessible at http://localhost:3000
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"   # Backend Django app will be accessible at http://localhost:8000
    networks:
      - app-network
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

networks:
  app-network:
    driver: bridge
